title: <p align="center"> Milan Patty </p>

logo: "/images/profile-pic (6).png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/milan-patty-50600119a/">LinkedIn</a> |
  <a href="https://github.com/MLP99">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Simon Business School, University of Rochester.
  <br><br>
  I am currently a Machine Learning Research Intern at Skim AI Technologies with a focus on NLP and Deep Learning research.
  <br><br>
  </p>

theme: jekyll-theme-minimal
